export const GET_BUS_MONGO_REQUEST = "GET_BUS_MONGO_REQUEST";
export const GET_BUS_MONGO_SUCCESS = "GET_BUS_MONGO_SUCCESS";
export const GET_BUS_MONGO_FAILURE = "GET_BUS_MONGO_FAILURE";

export const GET_BUS_MONGO_ID_SUCCESS = "GET_BUS_MONGO_ID_SUCCESS";